/**
 ******************************************************************************
 * @file           : main.c
 * @author         : Auto-generated by STM32CubeIDE
 * @brief          : Main program body
 ******************************************************************************
 * @attention
 *
 * Copyright (c) 2024 STMicroelectronics.
 * All rights reserved.
 *
 * This software is licensed under terms that can be found in the LICENSE file
 * in the root directory of this software component.
 * If no LICENSE file comes with this software, it is provided AS-IS.
 *
 ******************************************************************************
 */

#include <registers.h>
#include <stdint.h>

#if !defined(__SOFT_FP__) && defined(__ARM_FP)
  #warning "FPU is not initialized, but the project is compiling for an FPU. Please initialize the FPU before use."
#endif




int main(void)
{
	RCC_CFGR_t volatile * const p_rcc_cfg = (RCC_CFGR_t*) (RCC_ADDRESS | RCC_CFGR_OFFSET);

	/*
	 * 	NOTE: This section of code is for using HSE clock derived from ST-Link on board of 8 MHz.
	 */

	// Before Enabled HSE clock signal, set HSE Clock bypass.
	RCC_CR_t volatile * const p_rcc_cr = (RCC_CR_t*) (RCC_ADDRESS | RCC_CR_OFFSET);
//	p_rcc_cr->hse_byp = 0x01;	// Set bypass external clock signal
	p_rcc_cr->hse_on = 0x01;	// Enable HSE clock

	// Wait external clock for stable
	while(p_rcc_cr->hse_rdy != 0x01);

	// Change the system clock signal for HSE source
	p_rcc_cfg->sw = 0x01;

	// *****************************************************************************************


	// Configure MCO 1 signal
	// p_rcc_cfg->mco_1 = 0b00;		//	Set HSI clock as source.
	p_rcc_cfg->mco_1 = 0b10;		//	Set HSE clock as source.

	/*
	 * 	0b0xx	Not division
	 * 	0b100	Divided by 2
	 * 	0b101	Divided by 3.
	 * 	0b110	Divided by 4
	 * 	0b111	Divided by 5
	 */
	p_rcc_cfg->mco_1_pre = 0b111;	// 	Set clock source divided by 5.

	// Enable Clock peripheral for PORT A.
	RCC_AHB1ENR_t volatile * const p_rcc_ahb1_en = (RCC_AHB1ENR_t *) (RCC_ADDRESS | RCC_AHB1ENR_OFFSET);
	p_rcc_ahb1_en->GPIO_A_EN = 0x01;

	// Configure PORT A GPIO 8 for MCO 1 output using alternate function.
	GPIOx_MODER_t volatile * const p_gpio_a_moder = (GPIOx_MODER_t*) (GPIO_A_REGISTER | GPIO_MODER_OFFSET);
	p_gpio_a_moder->MODER_8 = 0b10;	// For alternate function mode.

	GPIOx_AFRH_t volatile * const p_gpio_a_afrh = (GPIOx_AFRH_t*) (GPIO_A_REGISTER | GPIO_AFRH_OFFSET);
	p_gpio_a_afrh->AFRH_8 = 0x0;	// Set alternate function 0.

	GPIOx_OSPEEDR_t volatile * const p_gpio_a_ospeed = (GPIOx_OSPEEDR_t*) (GPIO_A_REGISTER | GPIO_OSPEEDR_OFFSET);
	p_gpio_a_ospeed->ospeed_8 = 0b11;	// Set GPIO 8 as High Output Speed.


    /* Loop forever */
	for(;;);
}

