/**
 ******************************************************************************
 * @file           : main.c
 * @author         : Auto-generated by STM32CubeIDE
 * @brief          : Main program body
 ******************************************************************************
 * @attention
 *
 * Copyright (c) 2024 STMicroelectronics.
 * All rights reserved.
 *
 * This software is licensed under terms that can be found in the LICENSE file
 * in the root directory of this software component.
 * If no LICENSE file comes with this software, it is provided AS-IS.
 *
 ******************************************************************************
 */

#include <stdint.h>
#include <stdio.h>
#include <stdbool.h>

/*
 *  Define the Register Address
 */

#define RCC_REGISTER 			0x40023800
#define RCC_AHB1ENR_OFFSET 		0x00000030

#define GPIO_A_REGISTER 		0x40020000
#define GPIO_MODER_OFFSET		0x00000000
#define GPIO_ODR_OFFSET			0x00000014

/*
 * This code enables the AHP1 clock for GPIO port A (PA5) to turn ON a built-in led.
 */



#if !defined(__SOFT_FP__) && defined(__ARM_FP)
  #warning "FPU is not initialized, but the project is compiling for an FPU. Please initialize the FPU before use."
#endif

int main(void)
{

	// Create a pointer to AHP1 Clock for port GPIO A.
	uint32_t * rcc_enable_ahb1 = (uint32_t*) (RCC_REGISTER | RCC_AHB1ENR_OFFSET);
	printf("The pointer for RCC_REGISTER address is: %p \n", rcc_enable_ahb1);

	// Enables the AHP1 Clock for PORT GPIO A.
	*rcc_enable_ahb1 |= 0x01;

	// Create a pointer to GPIO A configuration.
	uint32_t * gpio_a_moder_register = (uint32_t*) (GPIO_A_REGISTER | GPIO_MODER_OFFSET);
	uint32_t * gpio_a_output_data_register = (uint32_t*) (GPIO_A_REGISTER | GPIO_ODR_OFFSET);

	// Set GPIO A pin 5 as output.
	*gpio_a_moder_register |= (1 << 10); //0x400;

	// Set GPIO A pin 5 in high state.
//	*gpio_a_output_data_register |= (1 << 5); //0x20;

    /* Loop forever */
	while(true)
	{
		for(uint32_t count = 0; count < (UINT16_MAX * 4); count ++ );
		*gpio_a_output_data_register ^= (0x01 << 5);
	}
}
