/**
 ******************************************************************************
 * @file           : main.c
 * @author         : Auto-generated by STM32CubeIDE
 * @brief          : Main program body
 ******************************************************************************
 * @attention
 *
 * Copyright (c) 2024 STMicroelectronics.
 * All rights reserved.
 *
 * This software is licensed under terms that can be found in the LICENSE file
 * in the root directory of this software component.
 * If no LICENSE file comes with this software, it is provided AS-IS.
 *
 ******************************************************************************
 */

#include <stdint.h>
#include <stdio.h>
#include "sys/types.h"

#if !defined(__SOFT_FP__) && defined(__ARM_FP)
  #warning "FPU is not initialized, but the project is compiling for an FPU. Please initialize the FPU before use."
#endif

int num = 750;

int main(void)
{

	printf("Hello World from Nucleo board using ITM FIFO over Serial Wire Debug. :D\n");

//	printf("\n\nTesting sizeof in STM32 microcontroller\n\n");
//
//	printf("The size of uint8: %d bytes\n", (int) sizeof(uint8_t));
//	printf("The size of u_int8: %d bytes\n", (int) sizeof(u_int8_t));
//
//	printf("The size of int: %d bytes\n", (int) sizeof(int));
//	printf("The size of short int: %d bytes\n", (int) sizeof(short int));
//	printf("The size of long int: %d bytes\n", (int) sizeof(long int));
//	printf("The size of char: %d bytes\n", (int) sizeof(char));
//	printf("The size of float: %d bytes\n", (int) sizeof(float));
//	printf("The size of double: %d bytes\n", (int) sizeof(double));
//	printf("The size of long double: %d bytes\n", (int) sizeof(long double));
//	printf("The size of long long: %d bytes\n", (int) sizeof(long  long));

	int * p_int = NULL;
	p_int = & num;
	printf("The size of pointer: %d bytes\n", (int) sizeof(p_int));
	printf("The address of pointer: %p \n", p_int);

    /* Loop forever */
	for(;;);
}
