/**
 ******************************************************************************
 * @file           : main.c
 * @author         : Auto-generated by STM32CubeIDE
 * @brief          : Main program body
 ******************************************************************************
 * @attention
 *
 * Copyright (c) 2024 STMicroelectronics.
 * All rights reserved.
 *
 * This software is licensed under terms that can be found in the LICENSE file
 * in the root directory of this software component.
 * If no LICENSE file comes with this software, it is provided AS-IS.
 *
 ******************************************************************************
 */

#include <stdint.h>
#include <stdio.h>
#include <stdbool.h>

#include "registers.h"


/*
 * This code enables the AHP1 clock for GPIO port A (PA5) to turn ON-OFF a built-in led  whether the state of PC4 pin is high or low.
 * The build settings for this project set a level of optimization -O2
 */



#if !defined(__SOFT_FP__) && defined(__ARM_FP)
  #warning "FPU is not initialized, but the project is compiling for an FPU. Please initialize the FPU before use."
#endif

int main(void)
{

	// Create a pointer to AHP1 Clock for port GPIO A.
	RCC_AHB1ENR_t volatile * const rcc_enable_ahb1 = (RCC_AHB1ENR_t*) (RCC_REGISTER | RCC_AHB1ENR_OFFSET);
	printf("The pointer for RCC_REGISTER address is: %p \n", rcc_enable_ahb1);

	// Enables the AHP1 Clock for PORT GPIO A.
	rcc_enable_ahb1->GPIO_A_EN = 0x01;

	// Enables the AHP1 Clock for PORT GPIO C.
	rcc_enable_ahb1->GPIO_C_EN = 0x01;

	// Create a pointers to GPIO A and C configuration.
	GPIOx_MODER_t volatile * const p_gpio_a_moder_register = 	(GPIOx_MODER_t*) (GPIO_A_REGISTER | GPIO_MODER_OFFSET);
	GPIOx_MODER_t volatile * const p_gpio_c_moder_register = 	(GPIOx_MODER_t*) (GPIO_C_REGISTER | GPIO_MODER_OFFSET);
	GPIOx_PUPDR_t volatile * const p_gpio_c_pupd_register = 	(GPIOx_PUPDR_t*) (GPIO_C_REGISTER | GPIO_PUPDR_OFFSET);

	// Set port A pin 5 as output.
	p_gpio_a_moder_register->MODER_5 = 0x01;

	// Set port C pin 4 (c4) as input with pull-down resistor.
	p_gpio_c_moder_register->MODER_4 = 0x00;
	p_gpio_c_pupd_register->PUPDR_4 = 0b00000010;

	volatile GPIOx_ODR_t * const p_gpio_a_output_data_register = (GPIOx_ODR_t*) (GPIO_A_REGISTER | GPIO_ODR_OFFSET);
	const volatile GPIOx_IDR_t *const p_gpio_c_input_data_register = (GPIOx_IDR_t*) (GPIO_C_REGISTER | GPIO_IDR_OFFSET);
	// Use type qualifier volatile to tells the compiler do not optimize this variable.

    /* Loop forever */
	while(true)
	{

		if( p_gpio_c_input_data_register->IDR_4 )	// Check state from PIN 4 in Port C.
		{
			p_gpio_a_output_data_register->ODR_5 = 0x01;	// Set LED PA5 in High State.
		}
		else
		{
			p_gpio_a_output_data_register->ODR_5 = 0x00;	// Set LED PA5 in Low State.
		}

	}
}
